sudo: false
language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      env: TOXENV=flake

    - python: 3.7
      dist: xenial
      env: TOXENV=py37

    - python: 3.7
      dist: xenial
      env: TOXENV=docs

install:
  - pip install tox

script:
  - tox